# These are supported funding model platforms

github: [Chakib-DAII]
patreon: Chakibd
open_collective: Naftah
ko_fi: chakibd
#tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
#community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
#liberapay: # Replace with a single Liberapay username
#lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
#polar: # Replace with a single Polar username
buy_me_a_coffee: chakibd
#thanks_dev: # Replace with a single thanks.dev username
