# frozen_string_literal: true

source "https://rubygems.org"

gem "jekyll", "~> 4.4"
gem "webrick", "~> 1.8"  # required for Ruby 3+
gem "minima", "~> 2.5.2" # base theme
gem "jekyll-sass-converter", "~> 2.1" # SCSS compilation
gem "jekyll-seo-tag", "~> 2.8" # SEO metadata
gem "jekyll-relative-links", "~> 0.6" # Optional: relative link handling
gem "jekyll-sitemap"